# Generated by Django 2.2.6 on 2020-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
